Repository INtiful/SootheWithMe, pull requests merged in 2024-09, with the labels that each got.

#3 feat: github actions 추가
  .github/CODEOWNERS
  .github/workflows/.gitkeep
  .github/workflows/ci.yml
  .github/workflows/lint.yml
Labels: ⚙️ Setting

#7 feat :tailwind color, font 설정
  .prettierrc
  src/app/layout.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ⚙️ Setting

#10 feat: 라이브러리 설치
  package-lock.json
  package.json
Labels: ⚙️ Setting

#14 feat: CD 관련한 GHA 추가
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  build.sh
Labels: ⚙️ Setting

#12 style: 이미지, 아이콘 파일 추가
  next.config.mjs
  package-lock.json
  package.json
  public/icons/.gitkeep
  public/icons/alarm.svg
  public/icons/arrow.svg
  public/icons/bye.svg
  public/icons/caret.svg
  public/icons/check.svg
  public/icons/checkbox-active.svg
  public/icons/checkbox-default.svg
  public/icons/dalaemfit.svg
  public/icons/heart.svg
  public/icons/icon-x.svg
  public/icons/index.ts
  public/icons/person.svg
  public/icons/save-active.svg
  public/icons/save-discard-btn.svg
  public/icons/save-discard.svg
  public/icons/save-inactive.svg
  public/icons/sort.svg
  public/icons/visivility-off.svg
  public/icons/visivility-on.svg
  public/icons/workation.svg
  public/images/.gitkeep
  public/images/btn-edit.svg
  public/images/head-class.svg
  public/images/head-review.svg
  public/images/head-saved.svg
  public/images/index.ts
  public/images/login-img.svg
  public/images/logo.svg
  public/images/profile-bg.svg
  public/images/profile-edit.svg
  public/images/profile.svg
  svg.d.ts
  tsconfig.json
Labels: ⚙️ Setting

#16 setting : CD 테스트 #2
  .github/workflows/cd.yml
Labels: ⚙️ Setting

#18 feat: 버튼, 드롭다운 컴포넌트 UI 작성
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/ISSUE_TEMPLATE/style.md
  .github/auto_assign.yml
  .gitignore
  package-lock.json
  package.json
  src/app/components/Button/Button.tsx
  src/app/components/DropDown/DropDown.tsx
  src/app/layout.tsx
  src/app/page.tsx
Labels: ✨ Feat

#19 feat: input, textarea 컴포넌트 UI 작성
  src/app/components/commons/input/Input.tsx
  src/app/components/commons/input/InputText.tsx
Labels: ✨ Feat

#23 feat: Box Select 컴포넌트 추가
  package-lock.json
  src/app/components/BoxSelect/BoxSelect.tsx
  tailwind.config.ts
Labels: ✨ Feat

#35 feat: Card list component 추가
  src/app/components/Card/Card.tsx
  src/app/components/CardList/CardList.tsx
  src/app/components/Tag/Tag.tsx
  src/types/data.type.ts
  src/utils/formatDate.ts
Labels: ✨ Feat

#36 feat: Bottom Floating Bar 컴포넌트 UI 작성
  src/app/components/BottomFloatingBar/BottomFloatingBar.tsx
  src/app/components/BottomFloatingBar/Mock.ts
  src/app/components/BottomFloatingBar/ParticipationButton.tsx
Labels: ✨ Feat

#39 feat: 마이페이지 프로필 컴포넌트 UI 작성
  src/app/components/Gnb/Gnb.tsx
  src/app/components/UserProfileLayout/Mock.ts
  src/app/components/UserProfileLayout/UserProfileLayout.tsx
Labels: ✨ Feat

#41 feat: gatherings 페이지 UI 작성 (미완성)
  src/app/(main)/gatherings/mockData/mockData.ts
  src/app/(main)/gatherings/page.tsx
  src/app/components/DropDown/DropDown.tsx
  src/app/components/Filter/FilterList.tsx
  src/app/components/Filter/FilterSort.tsx
  src/app/layout.tsx
  src/styles/globals.css
Labels: ✨ Feat

#43 feat: 공동 컴포넌트 - 모달, 팝업
  package-lock.json
  package.json
  src/app/components/BottomFloatingBar/Mock.ts
  src/app/components/BoxSelect/BoxSelect.tsx
  src/app/components/BoxSelect/BoxSelectGroup.tsx
  src/app/components/Button/Button.tsx
  src/app/components/Input/InputText.tsx
  src/app/components/Modal/CalendarModal.tsx
  src/app/components/Modal/MakeGatheringModal.tsx
  src/app/components/Modal/ProfileEditModal.tsx
  src/app/components/Modal/ReviewModal.tsx
  src/app/components/Popup/Popup.tsx
  src/app/layout.tsx
  src/styles/style.css
  tsconfig.json
Labels: ✨ Feat

#45 feat: 찜한 모임 페이지 UI
  src/app/(main)/saved/mockData.ts
  src/app/(main)/saved/page.tsx
  src/app/components/CardList/CardList.tsx
  src/app/components/DropDown/DropDown.tsx
  src/app/components/Filter/FilterList.tsx
  src/app/components/Filter/FilterSort.tsx
  src/app/components/Gnb/Gnb.tsx
  src/app/components/Tab/Tab.tsx
  src/app/layout.tsx
Labels: ✨ Feat

#48 feat: 모든 리뷰 페이지 UI
  src/app/(main)/reviews/_components/AverageRating.tsx
  src/app/(main)/reviews/_components/ScoreBar.tsx
  src/app/(main)/reviews/_components/Scores.tsx
  src/app/(main)/reviews/mockData.ts
  src/app/(main)/reviews/page.tsx
Labels: ✨ Feat

#49 feat: 모임 찾기 상세 페이지 UI 및 페이지네이션
  public/icons/chevron-left.svg
  public/icons/chevron-right.svg
  public/icons/index.ts
  src/app/(main)/gatherings/[id]/page.tsx
  src/app/(main)/gatherings/mockData/mockData.ts
  src/app/components/InformationCard/InformationCard.tsx
  src/app/components/Pagination/Pagination.tsx
  src/app/components/Review/Review.tsx
Labels: ✨ Feat

#50 feat: 로그인 회원가입페이지 zod 적용 및 애니메이션 구현
  package-lock.json
  package.json
  src/app/(auth)/_component/Footer.tsx
  src/app/(auth)/_component/FormField.tsx
  src/app/(auth)/_component/FormOptions.ts
  src/app/(auth)/layout.tsx
  src/app/(auth)/signin/_component/SignInForm.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/_component/SignUpForm.tsx
  src/app/(auth)/signup/page.tsx
  src/app/components/AuthForm/FormOptions.ts
  src/app/components/AuthForm/SignInForm.tsx
  src/app/components/AuthForm/SignUpForm.tsx
  src/app/components/Input/PasswordInput.tsx
  src/types/client.type.ts
  tailwind.config.ts
Labels: ✨ Feat

#55 setting: jest 환경 세팅
  jest.config.js
  package-lock.json
  package.json
  tsconfig.json
Labels: ⚙️ Setting

#56 test: Button UI 테스트 코드 작성
  src/app/components/Button/Button.test.tsx
  src/app/components/Button/Button.tsx
Labels: 🧪 Test

#57 test: DropDown UI 테스트 코드 작성
  src/app/components/DropDown/DropDown.test.tsx
  src/app/components/DropDown/DropDown.tsx
Labels: 🧪 Test

#59 test: Card, CardList 컴포넌트 테스트 코드 작성
  jest.config.js
  src/app/components/Card/Card.test.tsx
  src/app/components/Card/Card.tsx
  src/app/components/CardList/CardList.test.tsx
  src/app/components/CardList/CardList.tsx
  src/utils/formatDate.test.ts
  src/utils/formatDate.ts
  tsconfig.json
Labels: 🧪 Test

#60 test: Progress Bar 컴포넌트 테스트 코드 작성
  src/app/components/ProgressBar/ProgressBar.test.tsx
  src/app/components/ProgressBar/ProgressBar.tsx
Labels: 🧪 Test

#70 test: Popup 컴포넌트 테스트 코드 작성
  src/app/components/Popup/Popup.test.tsx
  src/app/components/Popup/Popup.tsx
Labels: 🧪 Test

#66 feat: 마이페이지 - 내가 만든 모임 페이지 UI
  src/app/(auth)/layout.tsx
  src/app/(main)/mypage/_component/Tab.tsx
  src/app/(main)/mypage/created/mockData.ts
  src/app/(main)/mypage/created/page.tsx
  src/app/(main)/mypage/layout.tsx
  src/app/layout.tsx
  src/styles/reset.css
Labels: ✨ Feat

#64 test: InformationCard UI 테스트 코드 작성
  src/app/components/InformationCard/Avatar.tsx
  src/app/components/InformationCard/InformationCard.test.tsx
Labels: 🧪 Test

#67 feat: 모임 만들기 페이지 추가
  src/app/(main)/gatherings/_component/ModalPlaceDropdown.tsx
  src/app/(main)/gatherings/page.tsx
  src/app/components/Card/Card.tsx
  src/app/components/CardList/CardList.tsx
  src/app/components/Chip/TimeChip.tsx
  src/app/components/DropDown/DropDown.tsx
  src/app/components/Gnb/Gnb.tsx
  src/app/components/InformationCard/InformationCard.tsx
  src/app/components/Input/Input.tsx
  src/app/components/Modal/MakeGatheringModal.tsx
  src/app/components/Modal/ModalFrame.tsx
  src/app/components/Modal/ModalPortal.tsx
  src/app/layout.tsx
  src/hooks/usePreventScroll.tsx
  src/styles/style.css
  tailwind.config.ts
Labels: ✨ Feat

#72 feat: 나의 모임 UI 구현
  package-lock.json
  package.json
  src/app/(main)/mypage/_component/MyGatheringList.tsx
  src/app/(main)/mypage/_component/fetch.tsx
  src/app/(main)/mypage/mockData/mockData.ts
  src/app/(main)/mypage/mygatherings/page.tsx
  src/app/api/mock/route.ts
  src/app/layout.tsx
  src/app/react-query-providers.tsx
  src/types/data.type.ts
Labels: ✨ Feat

#77 feat: 나의 리뷰 페이지 추가
  src/app/(main)/mypage/_component/ReviewFilterButtons.tsx
  src/app/(main)/mypage/_component/Tab.tsx
  src/app/(main)/mypage/created/mockData.ts
  src/app/(main)/mypage/created/page.tsx
  src/app/(main)/mypage/layout.tsx
  src/app/(main)/mypage/page.tsx
  src/app/(main)/mypage/review/mock.ts
  src/app/(main)/mypage/review/page.tsx
  src/app/components/Card/Card.tsx
  src/app/components/Modal/MakeGatheringModal.tsx
  src/app/components/Modal/ReviewModal.tsx
  src/app/components/Review/Review.tsx
  src/constants/common.ts
  src/styles/style.css
Labels: ✨ Feat

#74 refactor : Filter 컴포넌트 리팩토링
  src/app/(main)/saved/page.tsx
  src/app/components/Filter/Filter.test.tsx
  src/app/components/Filter/Filter.tsx
  src/app/components/Filter/FilterDate.test.tsx
  src/app/components/Filter/FilterDate.tsx
  src/app/components/Modal/CalendarModal.tsx
Labels: 🧩 Refactor

#75 feat: /gatherings 컴포넌트 리팩토링 및 모든 모임 불러오기 api 연결
  .env
  next.config.mjs
  src/app/(main)/gatherings/_component/ClientSideGatherings.tsx
  src/app/(main)/gatherings/_component/CreateGatheringButton.tsx
  src/app/(main)/gatherings/_component/Filters.tsx
  src/app/(main)/gatherings/_component/GatheringCardList.tsx
  src/app/(main)/gatherings/_component/Header.tsx
  src/app/(main)/gatherings/page.tsx
  src/app/actions/gatherings/fetchGatherings.ts
  src/app/components/Chip/Chip.tsx
  src/app/components/Chips/Chips.tsx
  src/app/components/Tabs/Tabs.tsx
Labels: ✨ Feat

#79 refactor : Card 컴포넌트 리팩토링
  src/app/(main)/mypage/_component/MyGatheringList.tsx
  src/app/(main)/mypage/created/page.tsx
  src/app/(main)/mypage/review/page.tsx
  src/app/components/Card/Card.test.tsx
  src/app/components/Card/Card.test.tsx.bak
  src/app/components/Card/Card.tsx
  src/app/components/Card/Card.tsx.bak
Labels: 🧩 Refactor

#88 feat: 로그인 회원가입 api 연결
  src/actions/auth/cookie/cookie.ts
  src/app/(auth)/_component/FormField.tsx
  src/app/(auth)/_component/FormOptions.ts
  src/app/(auth)/context/UserContext.tsx
  src/app/(auth)/signin/_component/SignInForm.tsx
  src/app/(auth)/signup/_component/SignUpForm.tsx
  src/app/api/auths/service/postSignIn.ts
  src/app/api/auths/service/postSignUp.ts
  src/app/api/auths/signin/route.ts
  src/app/api/auths/signup/route.ts
  src/app/components/Card/Card.tsx
  src/app/components/CardList/CardList.tsx
  src/app/layout.tsx
  src/app/providers.tsx
  src/types/client.type.ts
Labels: ✨ Feat

#89 feat: /gatherings 필터링 기능 구현
  src/app/(main)/gatherings/_component/ClientSideGatherings.tsx
  src/app/(main)/gatherings/_component/Filters.tsx
  src/app/(main)/gatherings/mockData/mockData.ts
  src/app/(main)/gatherings/page.tsx
  src/app/components/Chips/Chips.tsx
  src/app/components/DropDown/DropDown.tsx
  src/app/components/Filter/Filter.tsx
  src/app/components/Filter/FilterDate.tsx
  src/app/components/Filter/FilterList.tsx
  src/app/components/Filter/FilterSort.tsx
  src/constants/common.ts
  src/hooks/useGatherings.ts
  src/utils/formatDate.ts
  tailwind.config.ts
Labels: ✨ Feat

#92 feat : 모든 리뷰 페이지 기능 구현 (미완성)
  src/app/(main)/reviews/_components/AverageRating.tsx
  src/app/(main)/reviews/_components/Hearder.tsx
  src/app/(main)/reviews/_components/ReviewFilters.tsx
  src/app/(main)/reviews/_components/ReviewList.tsx
  src/app/(main)/reviews/_components/ReviewScore/AverageRating.tsx
  src/app/(main)/reviews/_components/ReviewScore/ReviewScore.tsx
  src/app/(main)/reviews/_components/ReviewScore/ScoreBar.tsx
  src/app/(main)/reviews/_components/ReviewScore/Scores.tsx
  src/app/(main)/reviews/_components/Scores.tsx
  src/app/(main)/reviews/mockData.ts
  src/app/(main)/reviews/page.tsx
  src/app/actions/reviews/getReviewList.ts
  src/app/actions/reviews/getReviewScore.ts
  src/app/components/Filter/FilterDate.tsx
  src/constants/common.ts
  src/types/data.type.ts
Labels: ✨ Feat

#93 feat: 모임 만들기 기능 추가
  src/app/api/actions/gatherings/postGatherings.ts
  src/app/components/BottomFloatingBar/Mock.ts
  src/app/components/BoxSelect/BoxSelect.tsx
  src/app/components/BoxSelect/BoxSelectGroup.tsx
  src/app/components/Modal/MakeGatheringModal.tsx
  src/app/components/Modal/MakeGatheringModal/BoxSelectGroup.tsx
  src/app/components/Modal/MakeGatheringModal/Calendar.tsx
  src/app/components/Modal/MakeGatheringModal/Header.tsx
  src/app/components/Modal/MakeGatheringModal/ImageUploader.tsx
  src/app/components/Modal/MakeGatheringModal/PlaceDropdown.tsx
  src/app/components/Modal/MakeGatheringModal/RecruitmentNumber.tsx
  src/app/components/Modal/MakeGatheringModal/SelectTimeChip.tsx
  src/constants/common.ts
  src/styles/style.css
  src/types/data.type.ts
Labels: ✨ Feat

#95 feat: /gatherings 페이지 무한스크롤 구현
  src/app/(main)/gatherings/_component/ClientSideGatherings.tsx
  src/app/(main)/gatherings/page.tsx
  src/app/api/actions/gatherings/getGatherings.ts
  src/app/components/Filter/FilterDate.tsx
  src/constants/common.ts
  src/hooks/useGatherings.ts
Labels: ✨ Feat

#94 feat: 마이페이지/내가 만든 모임 페이지 기능 구현
  src/app/(main)/mypage/created/_component/GatheringList.tsx
  src/app/(main)/mypage/created/mockData.ts
  src/app/(main)/mypage/created/page.tsx
  src/app/components/Card/Card.tsx
  src/types/data.type.ts
Labels: ✨ Feat

#98 feat: 찜한 모임 페이지 API 연동
  src/app/(main)/saved/_component/Chips.tsx
  src/app/(main)/saved/_component/Header.tsx
  src/app/(main)/saved/_component/SavedList.tsx
  src/app/(main)/saved/mockData.ts
  src/app/(main)/saved/page.tsx
  src/app/api/actions/gatherings/getGatherings.ts
  src/app/components/Badge/Badge.tsx
  src/app/components/CardList/CardList.test.tsx
  src/app/components/CardList/CardList.tsx
  src/app/components/Filters/Filters.tsx
  src/app/components/Gnb/Gnb.tsx
  src/app/components/Tab/Tab.tsx
  src/app/components/Tabs/Tabs.tsx
  src/app/layout.tsx
  src/app/providers.tsx
  src/context/SavedGatheringContext.tsx
  src/types/client.type.ts
Labels: ✨ Feat

#99 feat: /gatherings/[id] 기능 구현
  src/app/(auth)/context/UserContext.tsx
  src/app/(auth)/signup/_component/SignUpForm.tsx
  src/app/(main)/gatherings/[id]/_component/GatheringDetail.tsx
  src/app/(main)/gatherings/[id]/_component/GatheringImage.tsx
  src/app/(main)/gatherings/[id]/_component/GatheringReviews.tsx
  src/app/(main)/gatherings/[id]/page.tsx
  src/app/(main)/mypage/created/page.tsx
  src/app/api/actions/gatherings/deleteGatheringToWithdraw.ts
  src/app/api/actions/gatherings/getGatheringParticipants.ts
  src/app/api/actions/gatherings/postGatheringToJoin.ts
  src/app/api/actions/gatherings/putGatheringToCancelled.ts
  src/app/api/actions/reviews/fetchReviews.ts
  src/app/api/actions/reviews/getReviewList.ts
  src/app/api/actions/reviews/getReviewScore.ts
  src/app/components/BottomFloatingBar/BottomFloatingBar.tsx
  src/app/components/BottomFloatingBar/ParticipationButton.tsx
  src/app/components/InformationCard/InformationCard.tsx
  src/app/components/Popup/Popup.tsx
  src/app/components/Review/Review.tsx
  src/hooks/useCancelGathering.ts
  src/hooks/useCopyUrlToClipboard.ts
  src/types/client.type.ts
Labels: ✨ Feat

#97 feat: 마이페이지 및 gnb api 연결 및 프로필 수정 기능 추가
  src/app/(auth)/context/UserContext.tsx
  src/app/(auth)/signin/_component/SignInForm.tsx
  src/app/(auth)/signup/_component/SignUpForm.tsx
  src/app/api/actions/mypage/putProfileData.ts
  src/app/api/auths/signin/route.ts
  src/app/api/gatherings/joined/route.ts
  src/app/components/Gnb/Gnb.tsx
  src/app/components/Gnb/UserStatus.tsx
  src/app/components/InfiniteScroll/InfiniteScroll.tsx
  src/app/components/Modal/ProfileEditModal.tsx
  src/app/components/UserProfileLayout/Mock.ts
  src/app/components/UserProfileLayout/UserInfo.tsx
  src/app/components/UserProfileLayout/UserProfileHeader.tsx
  src/app/components/UserProfileLayout/UserProfileLayout.tsx
  src/app/components/UserProfileLayout/onChangeProfileImage.ts
  src/app/components/UserProfileLayout/useProfileState.ts
  src/constants/common.ts
  src/middleware.ts
Labels: ✨ Feat

#100 feat: 마이페이지 내 리뷰 관련 기능 추가
  src/app/(auth)/context/UserContext.tsx
  src/app/(main)/mypage/review/page.tsx
  src/app/api/actions/gatherings/getJoinedGathering.ts
  src/app/api/actions/reviews/getReviewList.ts
  src/app/api/actions/reviews/postReviews.ts
  src/app/components/Card/Card.tsx
  src/app/components/Modal/MakeGatheringModal.tsx
  src/app/components/Modal/ReviewModal.tsx
  src/constants/common.ts
  src/types/data.type.ts
Labels: ✨ Feat

#103 feat: css animation styling 적용
  src/app/(main)/gatherings/[id]/page.tsx
  src/app/(main)/gatherings/_component/GatheringCardList.tsx
  src/app/api/actions/gatherings/getGatheringParticipants.ts
  src/app/components/CardList/CardList.tsx
  src/app/components/InformationCard/InformationCard.tsx
  src/app/components/ProgressBar/ProgressBar.test.tsx
  src/app/components/ProgressBar/ProgressBar.tsx
Labels: ✨ Feat

#104 feat: 모든 리뷰 페이지 기능 구현
  src/app/(main)/reviews/_components/Chips.tsx
  src/app/(main)/reviews/_components/ClientSideReviews.tsx
  src/app/(main)/reviews/_components/Filters.tsx
  src/app/(main)/reviews/_components/ReviewFilters.tsx
  src/app/(main)/reviews/_components/ReviewList.tsx
  src/app/(main)/reviews/mockData.ts
  src/app/(main)/reviews/page.tsx
  src/app/actions/reviews/getReviewList.ts
  src/app/actions/reviews/getReviewScore.ts
  src/app/api/actions/reviews/getReviewList.ts
  src/app/api/actions/reviews/getReviewScore.ts
  src/constants/common.ts
  src/hooks/useReveiws.ts
Labels: ✨ Feat
