Repository INtiful/SootheWithMe, pull requests merged in 2024-10, with the labels that each got.

#110 fix: 모임 만들기 기능 수정
  src/app/api/actions/gatherings/postGatherings.ts
  src/app/components/Modal/MakeGatheringModal.tsx
  src/app/components/Modal/MakeGatheringModal/BoxSelectGroup.tsx
  src/app/components/Modal/MakeGatheringModal/Calendar.tsx
  src/app/components/Modal/MakeGatheringModal/ImageUploader.tsx
  src/app/components/Modal/MakeGatheringModal/SelectTimeChip.tsx
  src/app/components/Modal/ModalFrame.tsx
  src/app/components/Modal/ReviewModal.tsx
  src/constants/common.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: ⚒️ Fix

#109 refactor: useGatherings 훅 내부를 여러 훅으로 분리
  src/app/(main)/gatherings/[id]/page.tsx
  src/app/(main)/gatherings/_component/ClientSideGatherings.tsx
  src/app/(main)/gatherings/mockData/mockData.ts
  src/app/favicon.ico
  src/app/layout.tsx
  src/constants/common.ts
  src/hooks/useFetchFilteredGatherings.ts
  src/hooks/useGatherings.ts
  src/hooks/useHandlers.ts
  src/hooks/useLoadMore.ts
  src/hooks/useUpdateQueryParams.ts
  src/types/client.type.ts
Labels: 🧩 Refactor

#113 refactor : 찜한 모임 페이지 리팩토링
  src/app/(main)/gatherings/_component/GatheringCardList.tsx
  src/app/(main)/saved/_component/SavedList.tsx
  src/app/(main)/saved/page.tsx
  src/app/components/Gnb/Gnb.tsx
  src/app/components/InformationCard/InformationCard.tsx
  src/constants/common.ts
  src/hooks/useReveiws.ts
  src/hooks/useSavedGatherings.ts
  src/types/data.type.ts
Labels: 🧩 Refactor

#116 refactor : 마이페이지/내가 만든 모임 페이지 리팩토링
  src/app/(main)/mypage/created/_component/ClientSideGatherings.tsx
  src/app/(main)/mypage/created/_component/GatheringList.tsx
  src/app/(main)/mypage/created/page.tsx
  src/app/components/Card/Card.tsx
  src/hooks/useUserCreated.ts
Labels: 🧩 Refactor

#122 refactor : 모든 리뷰 페이지 리팩토링
  src/app/(main)/reviews/_components/ClientSideReviews.tsx
  src/app/(main)/reviews/_components/ReviewScore/AverageRating.tsx
  src/app/(main)/reviews/_components/ReviewScore/Scores.tsx
  src/app/(main)/reviews/_components/ReviewScore/calculates.ts
  src/app/(main)/reviews/mockData.ts
  src/app/(main)/saved/mockData.ts
  src/app/components/Card/Card.test.tsx.bak
  src/app/components/Card/Card.tsx.bak
  src/app/components/Filter/FilterList.tsx
  src/app/components/Filter/FilterSort.tsx
Labels: 🧩 Refactor

#115 fix: 로그인 상태에 따른 모임 만들기 버튼 로직 추가
  src/app/(main)/gatherings/_component/ClientSideGatherings.tsx
  src/app/(main)/gatherings/page.tsx
  src/app/components/BottomFloatingBar/ParticipationButton.tsx
  src/app/components/Modal/MakeGatheringModal.tsx
  src/app/layout.tsx
Labels: ⚒️ Fix

#120 refactor: 캘린더 커스텀 컴포넌트 추가
  src/app/components/Calendar/Calendar.tsx
  src/app/components/Modal/CalendarModal.tsx
  src/app/components/Modal/MakeGatheringModal.tsx
  src/app/components/Modal/MakeGatheringModal/Calendar.tsx
  src/app/components/Modal/MakeGatheringModal/CalendarSelect.tsx
  src/constants/common.ts
  src/utils/formatDate.ts
Labels: 🧩 Refactor

#121 feat: 토큰 만료 시 자동 로그아웃 기능 구현
  src/actions/auth/cookie/cookie.ts
  src/app/(auth)/signin/_component/SignInForm.tsx
  src/app/api/actions/mypage/getUserData.ts
  src/app/api/actions/mypage/postUserLogoutData.ts
  src/app/api/actions/mypage/putProfileData.ts
  src/app/components/Gnb/Gnb.tsx
  src/app/components/Gnb/TokenExpirationTimer.tsx
  src/app/components/Gnb/UserStatus.tsx
  src/app/components/Input/Input.tsx
  src/app/components/UserProfileLayout/UserProfileLayout.tsx
  src/app/layout.tsx
  src/constants/common.ts
  src/lib/clientRevalidate.ts
Labels: ✨ Feat

#123 refactor: 로딩 스피너, 에러 페이지, 토스트 관련 기능 구현
  next.config.mjs
  package-lock.json
  package.json
  src/app/(auth)/loading.tsx
  src/app/(main)/gatherings/[id]/_component/GatheringDetail.tsx
  src/app/(main)/gatherings/[id]/page.tsx
  src/app/(main)/gatherings/_component/ClientSideGatherings.tsx
  src/app/(main)/gatherings/error.tsx
  src/app/(main)/gatherings/loading.tsx
  src/app/api/actions/gatherings/deleteGatheringToWithdraw.ts
  src/app/api/actions/gatherings/getGatheringInfo.ts
  src/app/api/actions/gatherings/getGatheringParticipants.ts
  src/app/api/actions/gatherings/getGatherings.ts
  src/app/api/actions/gatherings/postGatheringToJoin.ts
  src/app/api/actions/gatherings/putGatheringToCancelled.ts
  src/app/components/BottomFloatingBar/ParticipationButton.tsx
  src/app/layout.tsx
  src/app/loading.tsx
  src/constants/toast.config.ts
  src/hooks/useCancelGathering.ts
  src/hooks/useCopyUrlToClipboard.ts
  src/hooks/useGatherings.ts
  src/hooks/useParticipation.ts
Labels: 🧩 Refactor

#126 fix: 그라데이션, chip 스타일링 변경, 찜 기능 변경, 초기 데이터 fetching 조건 변경
  src/app/(auth)/loading.tsx
  src/app/(main)/gatherings/_component/ClientSideGatherings.tsx
  src/app/(main)/gatherings/_component/GatheringCardList.tsx
  src/app/(main)/gatherings/loading.tsx
  src/app/(main)/gatherings/page.tsx
  src/app/api/actions/gatherings/getGatherings.ts
  src/app/components/Chips/Chips.tsx
  src/app/components/InformationCard/InformationCard.test.tsx
  src/app/components/InformationCard/InformationCard.tsx
  src/app/components/Loader/Loader.tsx
  src/app/loading.tsx
  src/utils/formatDate.ts
Labels: 🧩 Refactor

#127 Fix : 소규모 개선사항 및 버그 수정
  public/icons/dallaemfit.svg
  public/icons/index.ts
  src/app/(main)/gatherings/error.tsx
  src/app/(main)/mypage/created/mockData.ts
  src/app/(main)/reviews/_components/Chips.tsx
  src/app/(main)/saved/_component/Chips.tsx
  src/app/api/actions/gatherings/getGatherings.ts
  src/app/api/actions/reviews/getReviewList.ts
  src/app/api/actions/reviews/getReviewScore.ts
  src/app/components/CardList/CardList.test.tsx
  src/app/components/CardList/CardList.tsx
  src/app/components/Chips/Chips.tsx
  src/app/components/Tab/Tab.tsx
  src/app/components/Tabs/Tabs.tsx
  src/app/not-found.tsx
  src/hooks/useGatherings.ts
  src/hooks/useReveiws.ts
  src/types/client.type.ts
  src/types/data.type.ts
  tailwind.config.ts
Labels: ⚒️ Fix

#128 fix: 토큰 유효 기간이 끝나도 gnb에 타이머가 남아있는 문제해결
  src/app/(auth)/signin/_component/SignInForm.tsx
  src/app/components/Gnb/Gnb.tsx
  src/app/components/Gnb/TokenExpirationTimer.tsx
  src/app/components/Gnb/UserStatus.tsx
  src/constants/common.ts
Labels: ⚒️ Fix

#132 style: gnb 바 z-index 추가
  src/app/components/Gnb/Gnb.tsx
Labels: ⚒️ Fix

#131 [KAN-96] fix: getGathering api 요청 시 버그 수정
  src/app/(main)/mypage/created/page.tsx
  src/hooks/useSavedGatherings.ts
  src/hooks/useUserCreated.ts
Labels: ⚒️ Fix

#124 refactor: 리뷰 모달 컴포넌트 리팩토링
  src/app/api/actions/gatherings/postGatherings.ts
  src/app/api/actions/reviews/postReviews.ts
  src/app/components/Modal/MakeGatheringModal.tsx
  src/app/components/Modal/ModalHeader.tsx
  src/app/components/Modal/ProfileEditModal.tsx
  src/app/components/Modal/ReviewModal.tsx
  src/app/components/Modal/ReviewModal/CommentReview.tsx
  src/app/components/Modal/ReviewModal/HeartReview.tsx
  src/app/components/UserProfileLayout/UserProfileLayout.tsx
  src/app/providers.tsx
Labels: 🧩 Refactor

#134 refactor: Loader 컴포넌트 수정 및 적용
  src/app/(auth)/loading.tsx
  src/app/(main)/gatherings/_component/ClientSideGatherings.tsx
  src/app/(main)/gatherings/loading.tsx
  src/app/(main)/mypage/created/_component/ClientSideGatherings.tsx
  src/app/(main)/reviews/_components/ClientSideReviews.tsx
  src/app/components/Loader/Loader.tsx
  src/app/loading.tsx
Labels: 🧩 Refactor

#135 refactor: 모든 리뷰 페이지 리팩토링
  src/app/(main)/reviews/_components/ReviewScore/AverageRating.tsx
  src/app/(main)/reviews/_components/ReviewScore/calculates.ts
  src/app/api/actions/reviews/getReviewScore.ts
  src/types/data.type.ts
Labels: 🧩 Refactor

#146 refactor: Filters, Chips 컴포넌트를 공통 컴포넌트로 통합
  src/app/(main)/gatherings/_component/ClientSideGatherings.tsx
  src/app/(main)/gatherings/_component/Filters.tsx
  src/app/(main)/reviews/_components/Chips.tsx
  src/app/(main)/reviews/_components/ClientSideReviews.tsx
  src/app/(main)/reviews/_components/Filters.tsx
  src/app/(main)/saved/_component/Chips.tsx
  src/app/(main)/saved/page.tsx
  src/app/components/Chip/Chip.tsx
  src/app/components/Chips/Chips.tsx
  src/app/components/Filters/Filters.tsx
  src/hooks/useGatherings.ts
  src/hooks/useHandlers.ts
Labels: 🧩 Refactor

#150 feat: qs 라이브러리 적용
  package-lock.json
  package.json
  src/app/api/actions/gatherings/getGatherings.ts
  src/app/api/actions/gatherings/getJoinedGathering.ts
  src/app/api/actions/reviews/getReviewList.ts
  src/app/api/actions/reviews/getReviewScore.ts
  src/hooks/useSavedGatherings.ts
Labels: ✨ Feat

#149 test: BoxSelect 컴포넌트에 대한 테스트 코드 추가
  src/app/components/BoxSelect/BoxSelect.test.tsx
  src/app/components/BoxSelect/BoxSelect.tsx
Labels: 🧪 Test

#153 test: 마이페이지 유저프로필 테스트코드 작성
  src/app/components/UserProfileLayout/onChangeProfileImage.test.ts
  src/app/components/UserProfileLayout/useProfileState.test.ts
Labels: ⚒️ Fix

#142 fix: 리뷰 페이지 오류 수정
  src/app/(main)/mypage/_component/MyGatheringList.tsx
  src/app/(main)/mypage/_component/ReviewFilterButtons.tsx
  src/app/(main)/mypage/review/mock.ts
  src/app/(main)/mypage/review/page.tsx
  src/app/api/actions/reviews/postReviews.ts
  src/app/components/Modal/MakeGatheringModal.tsx
Labels: ⚒️ Fix

#143 fix: 로그아웃 및 타이머 끝날 때 타이머 및 유저데이터 초기화되지 않는 문제 해결
  src/app/components/Gnb/Gnb.tsx
  src/app/components/Gnb/TokenExpirationTimerLayout.tsx
  src/app/components/Gnb/UserStatus.tsx
  src/app/layout.tsx
  src/utils/TokenExpirationTimer.ts
Labels: ⚒️ Fix

#140 refactor: 모든 리뷰 커스텀 훅 리팩토링
  src/app/(main)/reviews/_components/ClientSideReviews.tsx
  src/app/(main)/reviews/_components/ReviewList.tsx
  src/app/(main)/reviews/_components/ReviewScore/AverageRating.tsx
  src/app/(main)/reviews/_components/ReviewScore/ReviewScore.tsx
  src/app/(main)/reviews/_components/ReviewScore/Scores.tsx
  src/app/(main)/reviews/page.tsx
  src/app/api/actions/reviews/getReviewList.ts
  src/app/api/actions/reviews/getReviewScore.ts
  src/app/components/Filter/FilterDate.tsx
  src/app/components/Modal/CalendarModal.tsx
  src/hooks/useReveiws.ts
  src/hooks/useReviews/buildParams.ts
  src/hooks/useReviews/useFilterState.ts
  src/hooks/useReviews/useReveiws.ts
  src/types/data.type.ts
Labels: 🧩 Refactor

#151 refactor: 내가 만든 모임 페이지 react-query 무한 스크롤 적용
  src/app/(main)/mypage/created/_component/ClientSideGatherings.tsx
  src/app/(main)/mypage/created/page.tsx
  src/hooks/useUserCreated.ts
Labels: 🧩 Refactor

#141 fix: 모임 생성 후 모임 상세페이지로 이동하는 기능 구현
  src/app/api/actions/gatherings/postGatherings.ts
  src/app/components/Modal/MakeGatheringModal.tsx
Labels: ⚒️ Fix

#157 refactor: 타입 공통화 작업
  src/app/(main)/gatherings/_component/ClientSideGatherings.tsx
  src/app/(main)/gatherings/_component/GatheringCardList.tsx
  src/app/(main)/mypage/created/_component/ClientSideGatherings.tsx
  src/app/(main)/mypage/created/_component/GatheringList.tsx
  src/app/(main)/saved/_component/SavedList.tsx
  src/app/api/actions/gatherings/getGatherings.ts
  src/app/components/CardList/CardList.test.tsx
  src/app/components/CardList/CardList.tsx
  src/hooks/useGatherings.ts
  src/hooks/useLoadMore.ts
  src/hooks/useSavedGatherings.ts
  src/hooks/useUserCreated.ts
  src/types/data.type.ts
Labels: 🧩 Refactor

#160 test: user profile layout 테스트코드 작성
  src/app/components/UserProfileLayout/UserInfo.test.tsx
  src/app/components/UserProfileLayout/UserProfileHeader.test.tsx
  src/app/components/UserProfileLayout/UserProfileLayout.test.tsx
  src/app/components/UserProfileLayout/useProfileState.test.ts
Labels: 🧪 Test

#159 feat: 모임 만들기 name 프로퍼티 추가
  src/app/components/Modal/MakeGatheringModal.tsx
  src/app/components/Modal/MakeGatheringModal/NameInput.tsx
Labels: ✨ Feat

#161 fix : 로그인 페이지 layoutshift 현상 해결
  src/app/(auth)/loading.tsx
  src/app/(main)/gatherings/loading.tsx
  src/app/loading.tsx
Labels: ⚒️ Fix

#165 fix: 지난 모임도 취소할 수 있는 기능 및 폰트 관련 에러 해결
  src/app/components/BottomFloatingBar/ParticipationButton.tsx
  src/app/components/InformationCard/InformationCard.tsx
  src/styles/globals.css
Labels: ⚒️ Fix

#152 feat: 다크 모드 세팅 및 /gatherings 다크 모드 적용
  package-lock.json
  package.json
  src/app/(main)/gatherings/page.tsx
  src/app/components/Chip/Chip.tsx
  src/app/components/Filter/Filter.tsx
  src/app/components/Filter/FilterDate.tsx
  src/app/components/Gnb/Gnb.tsx
  src/app/components/Modal/MakeGatheringModal.tsx
  src/app/components/Popup/Popup.tsx
  src/app/components/Tab/Tab.tsx
  src/app/layout.tsx
  src/app/theme-provider.tsx
  tailwind.config.ts
Labels: ✨ Feat

#167 test: bottom floating bar 테스트코드 작성
  src/app/components/BottomFloatingBar/BottomFloatingBar.test.tsx
  src/app/components/BottomFloatingBar/Mock.ts
  src/app/components/BottomFloatingBar/ParticipationButton.test.tsx
Labels: 🧪 Test

#169 refactor: 마이페이지 내 리뷰 관련 기능을 페이지로 분리
  src/app/(main)/mypage/_component/EmptyReviewPage.tsx
  src/app/(main)/mypage/_component/ReviewFilterButtons.tsx
  src/app/(main)/mypage/_component/ReviewFilterTab.tsx
  src/app/(main)/mypage/_component/Tab.tsx
  src/app/(main)/mypage/review/page.tsx
  src/app/(main)/mypage/review/writable/page.tsx
  src/app/(main)/mypage/review/written/page.tsx
  src/app/api/actions/gatherings/getJoinedGathering.ts
  src/app/components/Card/Card.tsx
  src/app/components/Modal/MakeGatheringModal.tsx
Labels: 🧩 Refactor

#170 refactor: InformationCard 컴포넌트 분리
  src/app/components/InformationCard/Avatars.tsx
  src/app/components/InformationCard/CapacityInfo.tsx
  src/app/components/InformationCard/DateTimeChips.tsx
  src/app/components/InformationCard/InformationCard.tsx
  src/app/components/InformationCard/InformationCardHeader.tsx
  src/app/components/InformationCard/ParticipantsInfo.tsx
  src/hooks/useFetchFilteredGatherings.ts
Labels: 🧩 Refactor

#177 feat: 모임 만들기 내 기능 추가 및 리팩토링
  src/app/components/Modal/MakeGatheringModal.tsx
  src/utils/objectCheckFalseValue.ts
  src/utils/objectExtractTrueValue.ts
Labels: ✨ Feat, 🧩 Refactor

#178 refactor: mypage 리팩토링
  src/app/(main)/mypage/_component/MyGatheringList.tsx
  src/app/(main)/mypage/loading.tsx
  src/app/(main)/mypage/page.tsx
  src/app/api/actions/gatherings/getMyGatherings.ts
  src/app/api/gatherings/joined/route.ts
  src/app/api/gatherings/service/getMyGathergins.ts
  src/app/components/BottomFloatingBar/BottomFloatingBar.test.tsx
  src/app/components/InfiniteScroll/InfiniteScroll.tsx
  src/app/components/Modal/ReviewModal.tsx
  src/app/layout.tsx
  src/constants/common.ts
  src/hooks/useParticipation.ts
  src/hooks/useReviews/useReveiws.ts
  src/hooks/useUserCreated.ts
Labels: ✨ Feat, 🧩 Refactor

#187 refactor: QueryKey Factory pattern 추가
  package-lock.json
  package.json
  src/app/(main)/mypage/_component/MyGatheringList.tsx
  src/app/(main)/mypage/review/writable/page.tsx
  src/app/api/gatherings/service/getMyGatherings.ts
  src/app/components/InfiniteScroll/InfiniteScroll.tsx
  src/app/providers.tsx
  src/hooks/useParticipation.ts
  src/hooks/useReviews/buildParams.ts
  src/hooks/useReviews/useFilterState.ts
  src/hooks/useReviews/useReveiws.ts
  src/hooks/useUserCreated.ts
  src/queries/index.ts
  src/queries/mypage/created.ts
  src/queries/mypage/joined.ts
  src/queries/mypage/writableReview.ts
  src/queries/review/review.ts
  src/types/client.type.ts
Labels: 🧩 Refactor

#186 feat: 모임 남은 일자 수 태그로 표시
  src/app/(main)/gatherings/[id]/_component/GatheringDetail.tsx
  src/app/(main)/gatherings/[id]/_component/GatheringImage.tsx
  src/app/(main)/gatherings/page.tsx
  src/app/api/actions/gatherings/getGatherings.ts
  src/app/components/CardList/CardList.test.tsx
  src/app/components/CardList/CardList.tsx
  src/app/components/Tag/Tag.tsx
  src/hooks/useGatherings.ts
  src/utils/getDaysUntilRegistrationEnd.ts
  src/utils/getTagMessage.ts
Labels: ✨ Feat

#185 refactor: 회원가입 로그인페이지 리팩토링
  public/images/login-img.svg
  src/app/(auth)/_component/FormField.tsx
  src/app/(auth)/_component/FormValidation.ts
  src/app/(auth)/context/UserContext.tsx
  src/app/(auth)/signin/_component/SignInForm.tsx
  src/app/api/actions/cookie/cookie.ts
  src/app/api/actions/gatherings/deleteGatheringToWithdraw.ts
  src/app/api/actions/gatherings/getJoinedGathering.ts
  src/app/api/actions/gatherings/getMyGatherings.ts
  src/app/api/actions/gatherings/postGatheringToJoin.ts
  src/app/api/actions/gatherings/postGatherings.ts
  src/app/api/actions/gatherings/putGatheringToCancelled.ts
  src/app/api/actions/mypage/getUserData.ts
  src/app/api/actions/mypage/putProfileData.ts
  src/app/api/actions/reviews/postReviews.ts
  src/app/api/auths/signin/route.ts
  src/app/api/gatherings/joined/route.ts
  src/app/components/Gnb/UserStatus.tsx
  src/app/components/Input/Input.test.tsx
  src/app/components/Input/Input.tsx
  src/app/components/Input/PasswordInput.test.tsx
  src/app/components/Input/PasswordInput.tsx
  src/app/layout.tsx
  src/app/providers.tsx
  src/middleware.ts
  src/utils/TokenExpirationTimer.ts
Labels: 🧩 Refactor

#184 test : msw, playwright 세팅 및 모든 리뷰 페이지 테스트
  .github/workflows/ci.yml
  .github/workflows/playwright.yml
  .gitignore
  jest.config.js
  next.config.mjs
  package-lock.json
  package.json
  playwright.config.ts
  public/mockServiceWorker.js
  src/__TEST__/reviews/page.test.tsx.bak
  src/app/(main)/reviews/_components/ReviewList.tsx
  src/app/(main)/reviews/_components/ReviewScore/AverageRating.tsx
  src/app/components/Tab/Tab.tsx
  src/instrumentation.ts
  src/msw/browser.ts
  src/msw/handlers.ts
  src/msw/reviews/filterReviews.ts
  src/msw/reviews/mockReviews.ts
  src/msw/server.ts
Labels: 🧪 Test

#188 Refactor: 리스트 컴포넌트 스크롤 시 그라데이션 효과
  src/app/(main)/gatherings/_component/GatheringCardList.tsx
  src/app/(main)/layout.tsx
  src/app/(main)/mypage/created/_component/GatheringList.tsx
  src/app/(main)/mypage/review/writable/page.tsx
  src/app/(main)/mypage/review/written/_component/ReviewsList.tsx
  src/app/(main)/mypage/review/written/page.tsx
  src/app/(main)/reviews/_components/ReviewList.tsx
  src/app/(main)/saved/_component/SavedList.tsx
  src/app/components/CardList/CardList.test.tsx
  src/app/components/GradientOverlay/GradientOverlay.tsx
  src/app/components/InfiniteScroll/InfiniteScroll.tsx
  src/app/components/ScrollTopButton/ScrollTopButton.tsx
  src/app/providers.tsx
  src/hooks/useScrollGradientEffect.ts
  tailwind.config.ts
Labels: ✨ Feat, 🧩 Refactor

#191 test: gnb 컴포넌트 테스트코드 작성
  src/app/components/Gnb/Gnb.test.tsx
  src/app/components/Gnb/Gnb.tsx
  src/app/components/Gnb/TokenExpirationTimerLayout.test.tsx
  src/app/components/Gnb/UserStatus.test.tsx
Labels: 🧪 Test

#192 feat: /gatherings/[id] 이미지에 스켈레톤 적용 및 framer motion 적용
  package-lock.json
  package.json
  src/app/(main)/gatherings/[id]/_component/GatheringImage.tsx
  src/app/(main)/gatherings/_component/GatheringCardList.tsx
  src/app/(main)/reviews/_components/ReviewList.tsx
  src/app/(main)/saved/page.tsx
  src/app/components/Filter/Filter.test.tsx
  src/app/components/Filter/Filter.tsx
  src/app/components/Filter/FilterDate.test.tsx
  src/app/components/Filter/FilterDate.tsx
  src/app/components/Modal/ModalFrame.tsx
  src/app/components/MotionWrapper/MotionWrapper.tsx
  src/app/components/Popup/Popup.tsx
  tailwind.config.ts
Labels: ✨ Feat

#195 remove: 미들웨어 삭제
  src/middleware.ts
Labels: ⚒️ Fix

#200 style: /mypage 에 motion animation 추가
  src/app/(main)/mypage/_component/MyGatheringList.tsx
  src/app/(main)/mypage/created/_component/GatheringList.tsx
  src/app/(main)/mypage/review/writable/page.tsx
  src/app/(main)/mypage/review/written/_component/ReviewsList.tsx
Labels: ✂️ Style

#201 fix: 모임 상세페이지 날짜 표시 형식 변경
  src/app/(main)/gatherings/[id]/_component/GatheringImage.tsx
  src/utils/getTagMessage.ts
Labels: ⚒️ Fix

#206 fix: /gatherings 필터링 관련 버그 수정
  src/app/components/Filter/Filter.tsx
  src/app/components/Filter/FilterDate.tsx
Labels: ⚒️ Fix

#190 docs: README 추가
  README.md
Labels: 📄 Docs

#202 fix: logout timer 버그 수정
  src/app/(main)/mypage/layout.tsx
  src/app/api/actions/mypage/putProfileData.ts
  src/app/api/gatherings/joined/route.ts
  src/app/components/Gnb/Gnb.tsx
  src/app/components/Gnb/UserStatus.test.tsx
  src/app/components/Gnb/UserStatus.tsx
  src/app/components/Modal/ProfileEditModal.tsx
  src/app/components/UserProfileLayout/UserProfileLayout.tsx
  src/utils/TokenExpirationTimer.ts
Labels: ⚒️ Fix, 🧩 Refactor

#209 fix: 리뷰 작성 후 해당 게시물 상세 페이지로 이동
  src/app/components/Modal/MakeGatheringModal.tsx
  src/app/components/Modal/ReviewModal.tsx
Labels: ⚒️ Fix

#215 setting : SEO 를 위한 세팅
  .env
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(main)/gatherings/[id]/page.tsx
  src/app/(main)/gatherings/page.tsx
  src/app/(main)/mypage/created/page.tsx
  src/app/(main)/mypage/layout.tsx
  src/app/(main)/mypage/page.tsx
  src/app/(main)/reviews/page.tsx
  src/app/(main)/saved/_component/SavedList.tsx
  src/app/(main)/saved/layout.tsx
  src/app/(main)/saved/page.tsx
  src/app/components/CardList/CardList.tsx
  src/app/layout.tsx
  src/app/robots.txt
  src/app/sitemap.ts
  src/utils/makeMetadata.ts
Labels: ⚙️ Setting

#214 fix: tag message 렌더링 수정
  src/app/(main)/gatherings/[id]/_component/GatheringDetail.tsx
  src/app/(main)/gatherings/[id]/_component/GatheringImage.tsx
  src/app/(main)/gatherings/[id]/page.tsx
  src/app/(main)/gatherings/_helpers/getDaysUntilRegistrationEnd.ts
  src/app/(main)/gatherings/_helpers/getTagMessage.ts
  src/app/(main)/gatherings/_helpers/isClosingTagVisible.ts
  src/app/(main)/gatherings/_helpers/isGatheringFull.ts
  src/app/components/CardList/CardList.test.tsx
  src/app/components/CardList/CardList.tsx
  src/constants/common.ts
  src/utils/getTagMessage.ts
Labels: ⚒️ Fix

#213 fix: 주최자일 때 예약취소 버튼 비활성화 및 모임취소 시 재확인 모달 추가
  src/app/(main)/mypage/_component/MyGatheringList.tsx
  src/app/components/BottomFloatingBar/ParticipationButton.test.tsx
  src/app/components/BottomFloatingBar/ParticipationButton.tsx
  src/app/components/Modal/CancelGatheringModal.tsx
Labels: ⚒️ Fix

#218 fix: 리뷰 작성하고 작성한 리뷰 페이지로 이동
  src/app/components/Modal/ReviewModal.tsx
Labels: ⚒️ Fix

#222 refactor: 접근성 개선을 위해 button에 aria-label 속성 추가
  src/app/components/Card/Card.tsx
  src/app/components/CardList/CardList.tsx
  src/app/components/Gnb/Gnb.tsx
  src/app/components/Gnb/ToggleTheme.tsx
  src/app/components/Input/Input.tsx
  src/app/components/Modal/CalendarModal.tsx
  src/app/components/Modal/ModalHeader.tsx
  src/app/components/Pagination/Pagination.tsx
  src/app/components/Popup/Popup.tsx
  src/app/components/Tab/TopTab.tsx
  src/app/components/UserProfileLayout/UserProfileHeader.tsx
Labels: 🧩 Refactor

#219 test: 모든 리뷰 페이지 e2e 테스트코드 작성
  src/__TEST__/reviews/page.test.tsx
  src/instrumentation.ts
  src/msw/handlers.ts
Labels: 🧪 Test

#223 fix: 로그아웃 타이머 및 로그아웃 관련 버그 수정
  src/app/components/Gnb/TokenExpirationTimerLayout.test.tsx
  src/app/components/Gnb/TokenExpirationTimerLayout.tsx
  src/app/components/Gnb/UserStatus.test.tsx
  src/app/components/Gnb/UserStatus.tsx
  src/utils/TokenExpirationTimer.ts
Labels: ⚒️ Fix

#224 fix: 날짜 비교 로직 수정
  src/app/(main)/gatherings/_helpers/getDaysUntilRegistrationEnd.ts
Labels: ⚒️ Fix

#226 fix: 마감 overlay 조건 수정 및 개설 확정 탭 뜨는 조건 수정
  src/app/components/CardList/CardList.tsx
  src/app/components/ProgressBar/ProgressBar.tsx
Labels: ✨ Feat, ⚒️ Fix
